name: Publish MkDocs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: you know material for mkdocs wasnt safe from my powershell
        shell: pwsh
        run: |
          $env:YES_MAKE_TONS_OF_FOLDERS=1
          ./redirector.ps1
          ./buildMap.ps1

          Get-ChildItem -File *.html -Recurse | ForEach-Object {
              $content = Get-Content -Path $_.FullName

              $content = $content -replace 'class="md-copyright">', 'class="md-copyright" style="display: none">'
              $content = $content -replace 'class="md-social">', 'class="md-social" style="margin: auto;">'

              Set-Content -Path $_.FullName -Value $content
          }

      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force -f mkdocs.github.yml
