name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🛠 Run the build script
        shell: pwsh
        # env:
        #   SUPER_SECRET: ${{ secrets.FUCK2 }}
        # Install-Module -Name powershell-yaml
        run: |
          
          Invoke-WebRequest -Uri "https://discord.com/api/webhooks/1002572530906833047/${{ secrets.FUCK2 }}" -Method Post -Body '{"content":"webhooks balls"}'  -Headers @{ "Content-Type" = "application/json" }

      - name: Commit modifications
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Autobuild