name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: /CTT CI
        shell: pwsh
        env:
          FUCK2: ${{ secrets.FUCK2 }}
          PROTO_BAR: ${{ secrets.PROTO_BAR }}
          PROTO_FOO: ${{ secrets.PROTO_FOO }}
          PROTO_ABOUT: ${{ secrets.PROTO_ABOUT }}
          PROTO_INSTRUCTIONS: ${{ secrets.PROTO_INSTRUCTIONS }}

        # Install-Module -Name powershell-yaml
        run: ./ci.ps1

      - name: Commit modifications of /docs/
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Autobuild