name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🛠 Run the build script
        shell: pwsh
        env:
          SUPER_SECRET: ${{ secrets.FUCK2 }}
        # Install-Module -Name powershell-yaml
        run: |
          
          & ./test.ps1

      - name: Commit modifications
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Autobuild